services:
  marquinhosbot:
    build: .
    env_file:
      - /etc/marquinhos/marquinhos.conf
    restart: on-failure:10
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    volumes:
      - /etc/ssl/dvns-certificate.pem:/etc/ssl/dvns-certificate.pem
      - /etc/ssl/dvns-private.pem:/etc/ssl/dvns-private.pem
