import type { Question } from 'services/activity/trivia-quiz/types';

const QUESTIONS: Question[] = [
  {
    id: 'q1',
    text: 'What is the capital of France?',
    options: ['London', 'Paris', 'Berlin', 'Madrid'],
    correctIndex: 1,
    category: 'Geography',
  },
  {
    id: 'q2',
    text: 'Which planet is the largest in our solar system?',
    options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'],
    correctIndex: 2,
    category: 'Astronomy',
  },
  {
    id: 'q3',
    text: 'What is the smallest country in the world?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctIndex: 1,
    category: 'Geography',
  },
  {
    id: 'q4',
    text: 'Who wrote "Romeo and Juliet"?',
    options: [
      'Christopher Marlowe',
      'William Shakespeare',
      'Ben Jonson',
      'John Webster',
    ],
    correctIndex: 1,
    category: 'Literature',
  },
  {
    id: 'q5',
    text: 'What is the chemical symbol for Gold?',
    options: ['Gd', 'Au', 'Ag', 'Go'],
    correctIndex: 1,
    category: 'Chemistry',
  },
  {
    id: 'q6',
    text: 'In what year did the Titanic sink?',
    options: ['1910', '1912', '1915', '1920'],
    correctIndex: 1,
    category: 'History',
  },
  {
    id: 'q7',
    text: 'What is the largest ocean on Earth?',
    options: [
      'Atlantic Ocean',
      'Indian Ocean',
      'Pacific Ocean',
      'Arctic Ocean',
    ],
    correctIndex: 2,
    category: 'Geography',
  },
  {
    id: 'q8',
    text: 'Which country has the most official languages?',
    options: ['India', 'South Africa', 'Papua New Guinea', 'Indonesia'],
    correctIndex: 2,
    category: 'Geography',
  },
  {
    id: 'q9',
    text: 'What is the speed of light?',
    options: ['300,000 m/s', '3,000 m/s', '30,000 m/s', '3,000,000 m/s'],
    correctIndex: 0,
    category: 'Physics',
  },
  {
    id: 'q10',
    text: 'Who was the first President of the United States?',
    options: [
      'Thomas Jefferson',
      'George Washington',
      'John Adams',
      'Benjamin Franklin',
    ],
    correctIndex: 1,
    category: 'History',
  },
  {
    id: 'q11',
    text: 'What is the capital of Japan?',
    options: ['Osaka', 'Tokyo', 'Kyoto', 'Yokohama'],
    correctIndex: 1,
    category: 'Geography',
  },
  {
    id: 'q12',
    text: 'How many strings does a violin have?',
    options: ['4', '5', '6', '8'],
    correctIndex: 0,
    category: 'Music',
  },
  {
    id: 'q13',
    text: 'What is the capital of Brazil?',
    options: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'],
    correctIndex: 2,
    category: 'Geography',
  },
  {
    id: 'q14',
    text: 'Who painted the Mona Lisa?',
    options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
    correctIndex: 1,
    category: 'Art',
  },
  {
    id: 'q15',
    text: 'What is the highest mountain in the world?',
    options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Makalu'],
    correctIndex: 1,
    category: 'Geography',
  },
  {
    id: 'q16',
    text: 'In what year did the Berlin Wall fall?',
    options: ['1987', '1988', '1989', '1990'],
    correctIndex: 2,
    category: 'History',
  },
  {
    id: 'q17',
    text: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
    category: 'Geography',
  },
  {
    id: 'q18',
    text: 'How many sides does a hexagon have?',
    options: ['5', '6', '7', '8'],
    correctIndex: 1,
    category: 'Mathematics',
  },
  {
    id: 'q19',
    text: 'What is the smallest prime number?',
    options: ['0', '1', '2', '3'],
    correctIndex: 2,
    category: 'Mathematics',
  },
  {
    id: 'q20',
    text: 'Who invented the telephone?',
    options: [
      'Thomas Edison',
      'Alexander Graham Bell',
      'Nikola Tesla',
      'Michael Faraday',
    ],
    correctIndex: 1,
    category: 'History',
  },
  {
    id: 'q21',
    text: 'What is the capital of Spain?',
    options: ['Barcelona', 'Valencia', 'Madrid', 'Seville'],
    correctIndex: 2,
    category: 'Geography',
  },
  {
    id: 'q22',
    text: 'How many continents are there?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    category: 'Geography',
  },
  {
    id: 'q23',
    text: 'What gas do plants absorb from the atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    correctIndex: 2,
    category: 'Biology',
  },
  {
    id: 'q24',
    text: 'In what year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    category: 'History',
  },
  {
    id: 'q25',
    text: 'What is the capital of Italy?',
    options: ['Milan', 'Rome', 'Venice', 'Florence'],
    correctIndex: 1,
    category: 'Geography',
  },
  {
    id: 'q26',
    text: 'How many bones does an adult human have?',
    options: ['186', '206', '226', '246'],
    correctIndex: 1,
    category: 'Biology',
  },
  {
    id: 'q27',
    text: 'What is the largest mammal in the world?',
    options: ['African Elephant', 'Giraffe', 'Blue Whale', 'Hippopotamus'],
    correctIndex: 2,
    category: 'Biology',
  },
  {
    id: 'q28',
    text: 'Who wrote "1984"?',
    options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Isaac Asimov'],
    correctIndex: 0,
    category: 'Literature',
  },
  {
    id: 'q29',
    text: 'What is the capital of Germany?',
    options: ['Munich', 'Hamburg', 'Cologne', 'Berlin'],
    correctIndex: 3,
    category: 'Geography',
  },
  {
    id: 'q30',
    text: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
    category: 'Mathematics',
  },
];

export function getQuestions(): Readonly<Question[]> {
  return QUESTIONS;
}

export function getQuestionById(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}
