services:
  marquinhos-web-api:
    env_file: !reset []
    environment:
      - NODE_ENV=development
    volumes:
      - ./.env:/app/apps/api/.env:ro
    ports:
      - "3106:3106"
    networks:
      - marquinhos-net

networks:
  marquinhos-net:
    external: true
